db_host = "nfss-mysql.cwwdolwzrjlq.us-east-2.rds.amazonaws.com"
db_database ="filehosting"
db_username="admin "
db_password = "netra_123"
aws_access_key_id = "AKIAXAAEAHAFGD6SIS7N"
aws_secret_access_key="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"